"""Passage events, rooms, devices, user access (spec-002/003)

Revision ID: 32a29bd3db70
Revises: 06574f9e432c
Create Date: 2026-08-09 00:27:53.752123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '32a29bd3db70'
down_revision: Union[str, None] = '06574f9e432c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), server_default='America/Sao_Paulo', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room')),
    sa.UniqueConstraint('slug', name=op.f('uq_room_slug'))
    )
    op.create_table('device',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_device_room_id_room')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device'))
    )
    op.create_table('passage_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('access_count', sa.BigInteger(), nullable=True),
    sa.Column('people_count', sa.BigInteger(), nullable=True),
    sa.Column('status_sensor', sa.String(length=50), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('pulse_ton', sa.Integer(), nullable=True),
    sa.Column('pulse_toff', sa.Integer(), nullable=True),
    sa.Column('raw_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_id'], ['data_tracker.id'], name=op.f('fk_passage_event_raw_id_data_tracker')),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_passage_event_room_id_room')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passage_event')),
    sa.UniqueConstraint('raw_id', name=op.f('uq_passage_event_raw_id'))
    )
    op.create_index('ix_passage_event_device_occurred', 'passage_event', ['device_id', 'occurred_at'], unique=False)
    op.create_index('ix_passage_event_room_occurred', 'passage_event', ['room_id', 'occurred_at'], unique=False)
    op.create_table('user_room',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_user_room_room_id_room')),
    sa.PrimaryKeyConstraint('user_id', 'room_id', name=op.f('pk_user_room'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_room')
    op.drop_index('ix_passage_event_room_occurred', table_name='passage_event')
    op.drop_index('ix_passage_event_device_occurred', table_name='passage_event')
    op.drop_table('passage_event')
    op.drop_table('device')
    op.drop_table('room')
    # ### end Alembic commands ###
